spring:
  rabbitmq:
    host: localhost
    password: admin
    username: admin

  cloud:
    stream:
      bindings:
        greetingChannel:
          destination: x.greeting
          contentType: application/json
        test-source:
          destination: x.test
          contentType: application/json